pull_request_rules:
- name: automatic merge
  conditions:
  - base=master
  - author=github-actions[bot]
  actions:
    merge:
      method: merge
- name: delete head branch after merge
  conditions: []
  actions:
    delete_head_branch: {}