name: Update dependencies
on:
  push:
    branches:
    - master
#  schedule:
#  - cron: '0 0 * * *'

jobs:
  up:
    name: mod up
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: cw-ozaki/github-action-test@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: up --build --pull-request
