name: update dependencies
on:
  schedule:
  - cron:  '*/5 * * * *'

jobs:
  up:
    name: mod up
    runs-on: ubuntu-18.04
    steps:
    - uses: cw-ozaki/github-action-test/up@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        entrypoint: sh
        args: -c 'pwd && ls -la'
